package com.maqueezu.el.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.maqueezu.el.entity.DBTestModel;

import com.maqueezu.el.dao.DBTestModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBTestModelDaoConfig;

    private final DBTestModelDao dBTestModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBTestModelDaoConfig = daoConfigMap.get(DBTestModelDao.class).clone();
        dBTestModelDaoConfig.initIdentityScope(type);

        dBTestModelDao = new DBTestModelDao(dBTestModelDaoConfig, this);

        registerDao(DBTestModel.class, dBTestModelDao);
    }
    
    public void clear() {
        dBTestModelDaoConfig.clearIdentityScope();
    }

    public DBTestModelDao getDBTestModelDao() {
        return dBTestModelDao;
    }

}
